ratelimit:
  rates:
    hotels:
      -
        key:  city
        duration_sec: 5
        limit: 10
        pause_sec: 5
      -
        key: room
        duration_sec: 10
        limit: 100
        pause_sec: 5
      -
        key: default
        duration_sec: 10
        limit: 50
        pause_sec: 5
    api2:
      -
        key: k1
        duration_sec: 5
        limit: 10
        pause_sec: 5
      -
        key: k2
        duration_sec: 10
        limit: 100
        pause_sec: 5
      -
        key: default
        duration_sec: 10
        limit: 50
        pause_sec: 5

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
#    initialization-mode: embedded
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#    generate-ddl: true
  h2:
    console:
      enabled: true